version: '3'
services:
############## Methods associated with serving files ##############
  reverse-proxy:
    build:
      context: ./reverse-proxy
      dockerfile: 'Dockerfile'
    restart: always
    depends_on:
      - authentication-server
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

############## Methods associated with user authentication ##############
  authentication-server:
    build: 
      context: ./authentication
      dockerfile: 'Dockerfile'
    env_file:
      - ./authentication/.env
    environment:
      - NODE_ENV='PRODUCTION'
    restart: always
    depends_on:
      - authentication-db
      # - authentication-cache

  authentication-db:
    restart: always
    image: mongo
    env_file:
      - ./authentication/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

  # authentication-cache:
  #   image: redis

####################### Live chat servers and services ######################
  live-chat-server:
    build: 
      context: ./live_chat
      dockerfile: 'Dockerfile'
    env_file:
      - ./live_chat/.env
    environment:
      - NODE_ENV='PRODUCTION'
    restart: always
    depends_on:
      - live-chat-db

  live-chat-db:
    restart: always
    image: mongo
    env_file:
      - ./authentication/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

