version: '3'
services:
############## Methods associated with serving files ##############
  reverse-proxy:
    build:
      context: ./reverse-proxy
      dockerfile: 'Dockerfile'
    restart: always
    depends_on:
      - authentication-server
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

############## Methods associated with user authentication ##############
  authentication-server:
    build: 
      context: ./authentication
      dockerfile: 'Dockerfile'
    env_file:
      - ./authentication/.env
    environment:
      - NODE_ENV='PRODUCTION'
    restart: always
    depends_on:
      - authentication-db
    # ports:
    #   - 3000:3000

  authentication-db:
    restart: always
    image: mongo
    env_file:
      - ./authentication/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
  # authentication-cache:
  #   image: redis:6.2-alpine
  #   restart: always
  #   ports:
  #     - '6379:6379'
  #   command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  #   volumes: 
  #     - cache:/data

####################### Live chat servers and services ######################
  live-chat-server:
    build: 
      context: ./live_chat
      dockerfile: 'Dockerfile'
    env_file:
      - ./live_chat/.env
    environment:
      - NODE_ENV='PRODUCTION'
    restart: always
    depends_on:
      - live-chat-db
    ports:
      - 3005:3005

  live-chat-db:
    restart: always
    image: mongo
    env_file:
      - ./live_chat/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}



####################### posts servers and services ######################
  posts-server:
    build: 
      context: ./posts
      dockerfile: 'Dockerfile'
    env_file:
      - ./posts/.env
    environment:
      - NODE_ENV='PRODUCTION'
    restart: always
    depends_on:
      - posts-db
  posts-db:
    restart: always
    image: mongo
    env_file:
      - ./posts/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

####################### Start up front end service ######################
  frontend-server:
    build: 
      context: ./frontend
      dockerfile: 'Dockerfile'
    environment:
      - NODE_ENV='PRODUCTION'
    restart: always
    depends_on:
      - posts-server
      - authentication-server
      - live-chat-server

# //! TODO: Enable caching
#           Mount voulms to local
#           Detemrine if the conenction is present.s