version: '3'
services:
  reverse-proxy:
    build:
      context: ./reverse-proxy
      dockerfile: 'Dockerfile'
    restart: always
    depends_on:
      - authentication-server
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  authentication-server:
    build: 
      context: ./authentication
      dockerfile: 'Dockerfile'
    env_file:
      - ./authentication/.env
    restart: always
    depends_on:
      - authentication-db

  authentication-db:
    restart: always
    image: mongo
    ports:
      - '2'

  # authentication-cache:
  #   image: 
